name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Prepare package version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Pack NuGet package
        run: |
          dotnet pack \
          --configuration Release \
          --no-build \
          --output nuget \
          --property:Version=${VERSION}

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push nuget/*.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate